spring.application.name=findfriends

 #Database Configuration (MySQL)
#spring.datasource.url=jdbc:mysql://localhost:3306/findfriends
#spring.datasource.username=root
#spring.datasource.password=2005
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


#PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/findfriends
spring.datasource.username=postgres
spring.datasource.password=2005
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate/JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect



spring.thymeleaf.cache=false
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

# PayOS Configuration
payos.client-id=0c4df1e5-9698-4573-b452-8c2ee3bccc05
payos.api-key=74562cd5-48b4-4e52-a7a6-c2e4c3d9b602
payos.checksum-key=a9939ebe1190b46fda8f0ade2e4fa324af4829621dd21a8591c0e220101b8cb8
payos.return-url=http://localhost:8080/payment/success
payos.cancel-url=http://localhost:8080/payment/cancel

# Force session tracking to only use cookies (disables appending ;jsessionid=... to URLs)
server.servlet.session.tracking-modes=cookie